---
title: "conditionals-model"
output: html_notebook
---

```{r setup}
source("constants.r")
source("data-processing-functions.r")
source("webppl-model.R")
source("helpers.R")
library(rwebppl)

create_target_dirs("plots")
create_target_dirs("data-samples")
create_target_dirs("data-models")
```

```{r run-model-function}
run_model <- function(lts, biases, alphas, n_runs=3, lawn_theta=0.05, bn_str='{table:[], cn:""}'){
  for(lt in lts){
    for(bias in biases) {
      for(alpha in alphas){
         if(bias=="douven1"){utt <- "If A, -C"}
          else{utt <- "If A, C"}
          
          fn <- paste(bias, lt, sep="-")
          if(bias=='lawn'){
            theta_lawn_str <- sub(".", "", as.character(lawn_theta), fixed = TRUE)
            fn <- paste(bias, theta_lawn_str, "-", lt, sep="")
          }
          if(lt=='PL'){
            fn <- paste(fn, "alpha", alpha, sep="-")
          }
          params_str <- setup(bias, utt, lt, alpha, lawn_theta, bn_str)
          webppl_model <- paste(MODEL, params_str, CALL_MODEL, sep="\n")
        
        for(i in seq(1, n_runs)){
          posterior <- webppl(webppl_model, random_seed=SEEDS[i])
          samples <- getSampleProbs(lt, posterior)
          
          target_model <-  get_target_dir("data-model", i)
          target_samples <- get_target_dir("data-samples", i) 

          saveRDS(samples, paste(target_samples, fn, "-run-", i, "-samples.rds", sep=""))
          saveRDS(posterior, paste(target_model, fn, "-run-", i, "-model.rds", sep=""))
        }
        
        # alpha has no influence on results for prior and literal listener
        if(lt=='prior' || lt=='LL'){break;}
      }
    }
  }
}

runSpeakerExpectation <- function(conditions, bias, alpha, n_run=1, lawn_theta=0.05){
  for(condition in conditions){
    params_str <- setup(bias, "dummy", "SE", alpha, lawn_theta)
    var_condition <- paste('var condition = "', condition, '"', sep="")
    webppl_model <- paste(MODEL, params_str, var_condition, CALL_MODEL, sep="\n")
    
    likelihoods <- webppl(webppl_model, random_seed=SEEDS[n_run])
    
    likelihoods.df <- as.data.frame(likelihoods)
    colnames(likelihoods.df) <- c("Group.1", "x")
    likelihoods.df$x <- unfactor(likelihoods.df$x)
    likelihoods.df$x <- round(as.numeric(likelihoods.df$x), digits=2)
    
    idx <- which(likelihoods.df$x!=0)
    likelihoods.df <- likelihoods.df[idx,]
    
    target_dir <- paste("../data/seed-", SEEDS[n_run], "/", sep="")
    fn <- get_filename(bias, "PL", alpha, n_run, lawn_theta)
    saveRDS(likelihoods.df, paste(target_dir, fn, "-SE-", condition, ".rds", sep=""))
  }
}

```

```{r run-model}
listenerTypes <- c("prior", "LL", "PL")
biases <- c("none", "lawn", "pizza", "douven1")
alphas = c(1, 3, 5, 10, 20)
run_model(listenerTypes, biases, alphas)

# Run model with bias=lawn with various bias thresholds
lawnThetas <- c(0.1, 0.2, 0.3, 0.4, 0.5)
for(theta in lawnThetas){
  run_model(listenerTypes, c("lawn"), alphas, lawn_theta=theta)
}

# TEST
listenerTypes <- c("prior", "LL", "PL")
biases <- c("lawn") #, "lawn", "pizza", "douven1")
alphas <- c(5)
n_runs <- 1
run_model(listenerTypes, biases, alphas, n_runs=1)

```

```{r run-speaker-expectation}
runSpeakerExpectation("no-condition", "douven1", 5)
runSpeakerExpectation("no-condition", "none", 5)
```


